apiVersion: v1
kind: Service
metadata:
  name: demo-service
  labels:
    app: demo-project
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: demo-project
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    app: demo-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-project
  template:
    metadata:
      labels:
        app: demo-project
    spec:
      containers:
      - name: demo-project
        image: <your-account-id>.dkr.ecr.us-east-1.amazonaws.com/demo-project:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5